# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_machines_machine_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='EmpId',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Machines',
        ),
    ]
